# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caff0cb61aed2595ac89d544a2215f08e4007a7b19c03e03719cae2ad18c19f4484987e346e6efa05fa5d30431ec9d31cf9e7217874545300b806c705565e590

test:
  secret_key_base: c9a5f2f214b96c5dd80b2ce9eff0284cb9705c6c0b027389a989467071418235d90654d24eec85f6038ce8020b3d9aa35f325b97069e56335e1224935e589b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
